- name: Deprovision VMs
  hosts: all
  gather_facts: false
  ignore_errors: true

  vars_files:
    - vault.yaml

  tasks:
    - name: Stop VMs
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        node: "{{ pve_node }}"
        vmid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        state: stopped

    - name: Remove VMs
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        node: "{{ pve_node }}"
        vmid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        state: absent

    - name: Remove stale SSH host key
      delegate_to: localhost
      become: false
      ansible.builtin.known_hosts:
        name: "{{ ansible_host }}"
        state: absent
