helm_apt_key_url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
helm_apt_key_id: DDF78C3E6EBB2D2CC223C95C62BA89D07698DBC6
helm_apt_keyring: /usr/share/keyrings/helm.gpg
helm_apt_repo: "deb [signed-by={{ helm_apt_keyring }}] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
helm_apt_sources: /etc/apt/sources.list.d/helm-stable-debian.list