- name: Setup K8S cluster with defaults
  hosts: localhost

  vars_files:
    - ../vault/vault.yaml

  environment: 
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig_location }}"
  tasks:
  - name: Deploy latest version of cert-manager
    kubernetes.core.helm:
      name: cert-manager
      chart_ref: oci://quay.io/jetstack/charts/cert-manager
      chart_version: v1.20.3
      release_namespace: cert-manager
      create_namespace: true
      release_state: present
      values:
        crds:
          enabled: true
      wait: true

  # create cluster issuer
  - name: Deploy cloudflare token
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: cloudflare-api-token-secret
          namespace: cert-manager
        type: Opaque
        stringData:
          api-token: "{{ cloudflare_api_token }}"

  - name: Deploy LE Cluster Issuer
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_resources }}/cert-manager/le-clusterissuer.yaml"

  - name: Deploy LE Staging Cluster Issuer
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_resources }}/cert-manager/le-staging-clusterissuer.yaml"

  - name: Setup kube-vip RBAC
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_resources ~ '/kube-vip/rbac.yaml' }}"
  - name: Deploy kube-vip
    kubernetes.core.k8s:
      state: present
      src: "{{ kubernetes_resources ~ '/kube-vip/deployment.yaml' }}"

