- name: Setup Jellyfin
  hosts: localhost

  vars_files:
    - ../vault/vault.yaml

  vars:
    base_url: "media.k3s.jordanhome.dev"
    issuer: "letsencrypt"

  environment: 
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig_location }}"

  tasks:
  - name: Create Jellyfin namespace
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', kubernetes_resources ~ '/jellyfin/namespace.yaml.j2') | from_yaml }}"

  - name: Setup Media library NFS PV
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', kubernetes_resources ~ '/jellyfin/media-library-pv.yaml.j2') | from_yaml }}"

  - name: Setup Media library NFS PVC
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', kubernetes_resources ~ '/jellyfin/media-library-pvc.yaml.j2') | from_yaml }}"

  - name: Setup Config backup NFS PVC
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', kubernetes_resources ~ '/jellyfin/media-config-backups-pvc.yaml.j2') | from_yaml }}"

  - name: Add jellyfin repo
    kubernetes.core.helm_repository:
      name: jellyfin
      repo_url: https://jellyfin.github.io/jellyfin-helm

  - name: Clone Jellyfin helm template
    ansible.builtin.template:
      src: "{{ kubernetes_resources }}/jellyfin/helm.yaml.j2"
      dest: "{{ root_dir }}/.tmp/jellyfinhelm.yaml"

  - name: Deploy Jellyfin
    kubernetes.core.helm:
      name: jellyfin
      chart_ref: jellyfin/jellyfin
      release_namespace: jellyfin
      create_namespace: true
      release_state: present
      wait: true
      values_files: "{{ root_dir }}/.tmp/jellyfinhelm.yaml"

  - name: Deploy Sonarr
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/sonarr/*.yaml.j2"

  - name: Deploy Radarr
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/radarr/*.yaml.j2"

  - name: Deploy Prowlarr
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/prowlarr/*.yaml.j2"

  - name: Deploy Bazarr
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/bazarr/*.yaml.j2"

  - name: Deploy Qbittorrent
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/qbittorrent/*.yaml.j2"

  - name: Deploy Jellyseerr
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', item) | from_yaml }}"
    with_fileglob:
      - "{{ kubernetes_resources }}/jellyseerr/*.yaml.j2"
