- name: Provision VMs
  hosts: all
  gather_facts: false

  vars:
    template_vmid:
      node0: 9000
      node1: 9001

  vars_files:
    - ../vault/vault.yaml

  tasks:
    - name: Clone template
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        clone: debian-template
        full: false

        node: "{{ pve_node }}"
        vmid: "{{ template_vmid[pve_node] }}"
        newid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        state: present
    - name: Stop VMs to configure networking
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        node: "{{ pve_node }}"
        vmid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        state: stopped
    - name: Configure networking
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        node: "{{ pve_node }}"
        vmid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        update: true
        update_unsafe: true

        net:
          net0: "virtio,bridge=vmbr0"

        searchdomains: ''

        ipconfig:
          ipconfig0: "ip={{ ansible_host }}/24,gw=192.168.1.1"

        state: present

    - name: Start VMs
      delegate_to: localhost
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_token_id: ansible-api
        api_token_secret: "{{ pve_api_key }}"

        validate_certs: false

        node: "{{ pve_node }}"
        vmid: "{{ vmid }}"
        name: "{{ inventory_hostname }}"

        state: started

    - name: Wait for SSH
      ansible.builtin.wait_for_connection:
        timeout: 180

    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
