pve_api_host: 192.168.1.160
pve_api_user: ansible@pve

ansible_user: jtwylde
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"