
# Proxmox
pve_api_host: 192.168.1.160
pve_api_user: ansible@pve

# Ansible defaults
ansible_user: jtwylde
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_python_interpreter: /usr/bin/python3.13
root_dir: "{{ playbook_dir | ansible.builtin.dirname }}"

# Kubernetes
k3s_master_node: "{{ hostvars[groups['k3s_nodes'][0]].ansible_host }}"
kubeconfig_location: "{{ root_dir }}/.config/kubeconfig.yaml"
kubernetes_resources: "{{ root_dir }}/kubernetes_resources"
k3s_vip_address: 192.168.1.175